#!/usr/bin/env python3

from itertools import product


def euler029():
    """
    --- Distinct Powers ---
    How many distinct terms are in the sequence generated by a ** b
    for 2 <= a <= 100 and 2 <= b <= 100
    """
    output = set()          # Using set to throw out duplicates
    values = range(2, 101)  # Value range for both a and b

    for a, b in product(values, values):
        output.add(a**b)

    return len(output)


if __name__ == "__main__":
    print(euler029())